[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vaux-cli"
version = "0.1.29"
description = "A terminal client for vaux listening rooms."
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "Violet Nguyen", email = "nviolet0120@gmail.com" },
]
license = "MIT"
dependencies = [
    "click",
    "textual",
    "python-socketio[asyncio_client]",
    "httpx",
    "yt-dlp>=2026.3.17",
    "pyperclip",
]

[project.urls]
Homepage = "https://github.com/itsvee0120/vaux"

[project.scripts]
vaux = "main:cli"

[tool.setuptools]
packages = ["vaux"]
py-modules = ["main"]

[tool.setuptools.package-data]
vaux = ["room_slug_words.json"]